### ISSUE TITLE
[Feature Request]: Individual permissions per app

### ISSUE THREAD

**Issue by nholloh** [tryzealot/zealot#1494]
### 描述 | Description

Hi @icyleaf

thanks for your work on zealot! We're currently considering it as part of our endeavour to migrate off of AppCenter. What really makes zealot stand out is that is allows for resigning of iOS apps to account for new iOS test devices. Unfortunately there is an additional requirement from our IT operations side: to be able to assign users or user groups to certain apps and therefore effectively limit what apps they can access. Spelled out that would mean:

- Give a role to a user for a particular app (user A could be Admin on the app Foo, but only User of App Bar)
- Assign and revoke roles for users and apps through the REST API

Ideally, we'd additionally be able to:

- Create user groups
- Assign and revoke roles for users and user groups (user group App_Foo_Test has role User, App_Foo_Dev has role Developer)
- Assign to and revoke membership of users for user groups
- Assign to and revoke membership of users for user groups trough the REST API

Do you think that these features would add value to zealot?

Thanks :)

**Comment by icyleaf** [comment]
The lack of fine-grained permission segmentation has always been a significant part. In essence, the underlying structure has already established the relationship between users and applications. However, due to the lack of clear understanding, it has not been realized until now. Instead, only a very coarse-grained global permission has been implemented, and all of these are hard-coded logic. To implement new logic, it would require substantial changes.

**Comment by nholloh** [comment]
Is there anything I can do to help build understanding or how I can contribute to the project? I‘m an iOS engineer and my ruby experience is at best limited, especially with rails. But if there’s anything I can assist with let me know.

**Comment by icyleaf** [comment]
Feature was merged, use `nightly` tag to try it after the [action](https://github.com/tryzealot/zealot/actions/runs/9183699952) is finished.

**Comment by icyleaf** [comment]
The version 5.3.0 will be released ASAP.

**Comment by icyleaf** [comment]
Close for now, re-open it if any issue.
