### ISSUE TITLE
[Feature Request]: Added the api to get the latest version

### ISSUE THREAD

**Issue by rakuyoMo** [tryzealot/zealot#1751]
### 描述 | Description

I hope there are two forms, web page and download link.

The current download link format is: https://tryzealot.ews.im/download/releases/17

I hope to add a format: `https://tryzealot.ews.im/download/releases/#{channel_slug}/last`, through which you can download the latest installation package of a channel.

In addition, I also hope to add `https://tryzealot.ews.im/{channel_slug}/last`, through which you can directly access the details page of the latest package of the channel.

Thanks to the author 🙏

**Comment by icyleaf** [comment]
> I hope to add a format: https://tryzealot.ews.im/download/releases/#{channel_slug}/last, through which you can download the latest installation package of a channel.

This is not considered an API endpoint， it's an address within the web service. Adding this link is not recommended because it would require additional permission/policy controls. It's suggested to use the existing API instead.

> In addition, I also hope to add https://tryzealot.ews.im/{channel_slug}/last, through which you can directly access the details page of the latest package of the channel.

It always redirect to the lastest build with http://{host}/{channel_slug} url rule.

**Comment by rakuyoMo** [comment]
> It always redirect to the lastest build with `http://{host}/{channel_slug}` url rule.

Ok, that's enough, it will help a lot of people. Thanks a lot!
